name: Terraform

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Set environment variables
      id: vars
      run: |
        if [ "${GITHUB_REF##*/}" == "dev" ]; then
          echo "TF_VAR_storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_DEV }}" >> $GITHUB_ENV
          echo "TF_VAR_storage_access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY_DEV }}" >> $GITHUB_ENV
        elif [ "${GITHUB_REF##*/}" == "test" ]; then
          echo "TF_VAR_storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_TEST }}" >> $GITHUB_ENV
          echo "TF_VAR_storage_access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY_TEST }}" >> $GITHUB_ENV
        elif [ "${GITHUB_REF##*/}" == "main" ]; then
          echo "TF_VAR_storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_MAIN }}" >> $GITHUB_ENV
          echo "TF_VAR_storage_access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY_MAIN }}" >> $GITHUB_ENV
        fi
        echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init -backend-config="storage_account_name=$TF_VAR_storage_account_name" -backend-config="container_name=terraform-state" -backend-config="key=terraform.tfstate" -backend-config="access_key=$TF_VAR_storage_access_key"
      working-directory: iac

    - name: Terraform Plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform plan -var-file="${{ env.BRANCH_NAME }}.tfvars"
      working-directory: iac
      timeout-minutes: 15

    - name: Terraform Apply
      if: always()
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform apply -var-file="${{ env.BRANCH_NAME }}.tfvars" -auto-approve
      working-directory: iac
      timeout-minutes: 15
